### PR TITLE
Modify unreachable cabal website links

### PR DESCRIPTION
**Pull request by July541**
Hello,
This pr is about the modification of cabal docs as they have changed their links from stable to latest, the previous is not available, I made it correct.

### CODE REVIEW

**Review by jneira — APPROVED** [review]
@July541 many thanks for the correction
(btw you could had changed the previous pr with a force push and renaming it in github but open a new one it is fine too)

**Comment by jneira** [comment]
Just for being complete:
* urls were changed following the cabal issue: https://github.com/haskell/cabal/issues/6966
* afaiu the disabling of stable urls is temporary and they will be restored
* we should return to stable urls as soon they are available

**Comment by July541** [comment]
> @July541 many thanks for the correction
> (btw you could had changed the previous pr with a force push and renaming it in github but open a new one it is fine too)

Thank you for your advice to a rookie!

**Review by fendor — APPROVED** [review]
Thank you!

**Pull request merged**
