### PR TITLE
WIP: Hie bios docker support

### PR DESCRIPTION
**Pull request by fendor**
Currently with hard-coded arguments for the output file in docker mode. 
Does not work for me, in a project with docker enabled, I currently get the error message:
```
⨯ hie-bios check src/Lib.hs                                               
hie-bios: hie-bios: can't find a package database at /opt/ghc/8.6.4/lib/ghc-8.6.4/package.conf.d
```
The output file looks like this for me:
```
⨯ cat out
/home/baldr/Documents/haskell/fprog
--interactive
-i
-odir=/home/baldr/Documents/haskell/fprog/.stack-work/odir
-hidir=/home/baldr/Documents/haskell/fprog/.stack-work/odir
-hide-all-packages
-i/home/baldr/Documents/haskell/fprog/.stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-2.4.0.1/build
-i/home/baldr/Documents/haskell/fprog/src
-i/home/baldr/Documents/haskell/fprog/.stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-2.4.0.1/build/autogen
-i/home/baldr/Documents/haskell/fprog/.stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-2.4.0.1/build/global-autogen
-stubdir=/home/baldr/Documents/haskell/fprog/.stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-2.4.0.1/build
-package-id=base-4.12.0.0
-package-id=containers-0.6.0.1
-package-id=data-ordlist-0.4.7.0-JijOptHq8X5AysaK6Liyhk
-optP-include
-optP/home/baldr/Documents/haskell/fprog/.stack-work/ghci/1930ce2a/cabal_macros.h
-ghci-script=/tmp/haskell-stack-ghci/834e85f2/ghci-script
```

Aims to fix https://github.com/digital-asset/ghcide/issues/221#issuecomment-565626118

### CODE REVIEW

**Comment by mpickering** [comment]
Where does that path come from?

**Comment by mpickering** [comment]
Perhaps this will never work of the packaged are only in scope inside the container. You would have to run the IDE inside the container as well.

**Comment by fendor** [comment]
No idea where this path comes from.

Yeah, that would definitely work.

**Comment by mpickering** [comment]
And if you run the IDE inside the same container then the stack support will work without any modifications I think.

**Comment by mpickering** [comment]
Closing as out-of-scope.

**Pull request closed without merging**
