### PR TITLE
Load plugins

### LINKED ISSUE #16: hie-bios doesn't enable GHC plugins
`loadFile` will fail on modules that require a GHC plugin to compile. It doesn't seem to respect `-fplugin` options set in either the cradle or via `OPTIONS_GHC`.

### PR DESCRIPTION
**Pull request by isovector**
Fixes #16

### CODE REVIEW

**Comment by isovector** [comment]
@mpickering you suggested on IRC that this might not be the right solution. It's pretty slow on my end, wondering if the speed is due to this not being right.

**Comment by mpickering** [comment]
How slow are we talking here? I don't think my idea would make it any faster.

**Comment by isovector** [comment]
We're talking my editor is unusable on a moderately sized project with ~15 modules. My guess is that `load` isn't caching unchanged modules.

**Comment by isovector** [comment]
(but i haven't dug into the perf; was just sorta hoping you'd divine the right answer :) )

**Comment by mpickering** [comment]
You need to pass the right flags to make it cache interface files. Are you passing `-fwrite-interface -hidir=...`?

**Comment by mpickering** [comment]
You are also supposed to cache the result of calling `findCradle`. If you don't do that it will be very slow

**Comment by mpickering** [comment]
I'm going to look into this after #53 is merged.

**Comment by mpickering** [comment]
I tried out the current master with a simple plugin which just calls error. By invoking `hie-bios` using the `check` command it simulates an initialisation followed by a simple call to `loadFile`. 

In both cases, plugin enabled in module and plugin enabled in cabal file, the load certainly invoked the plugin. 

Can you please provide a sample project that we can try to reproduce this issue?

**Comment by mpickering** [comment]
I put up a more refined version of this patch in #74

**Pull request closed without merging**
