### PR TITLE
Implement HIE_BIOS_GHC

### LINKED ISSUE #270: Proposal: faster Bios protocol
Currently the Bios protocol can involve two process calls: one asking for the flags/targets and another asking for the deps. This split means that the Bios program may need to implement some stateful caching in order to respond efficiently to the second request. 

The proposal is to merge both calls into a single one using two env vars: `HIE_BIOS_FLAGS` and `HIE_BIOS_DEPS`. I would add a third output value, the path to ghc, in an env var `HIE_BIOS_GHC_PATH`.

### PR DESCRIPTION
**Pull request by pepeiborra**
Closes #270

### CODE REVIEW

**Comment by pepeiborra** [comment]
This is ready for review

**Comment by adamse** [comment]
Looks like this also makes a nice solution for https://github.com/mpickering/hie-bios/issues/253

**Comment by fendor** [comment]
Ill see that I review it tomorrow. 

So far the main changes are:

* remove `runGhcCmd` from `Cradle a`
* add `componentRunGhcCmd` for `ComponentOptions`
* add `HIE_BIOS_GHC` output variable for cradle actions.
* Adds some instances for `CradleLoadResult`

Did I catch most changes?

**Comment by fendor** [comment]
I am worrying this breaks the HLS  wrapper.

Afaik, the flow is as follow:

* Find `hie.yaml`
* Use `runGhcCmd` to find the ghc version
* Launch the correct HLS version

How would that work with `componentRunGhcCmd`?

* Find `hie.yaml`
* Find some component?
* Use `componentRunGhcCmd` to find the ghc version
* Launch the correct HLS version

**Comment by pepeiborra** [comment]
> How would that work with `componentRunGhcCmd`?

Presumably the wrapper is always invoked with an input file, right? So the flow would be

* Find `hie.yaml`
* Find the local cradle
* Load the file with the cradle, resulting in some `ComponentOptions`
* Use `componentRunGhcCmd` to find the ghc version
* Launch the correct HLS version

**Comment by pepeiborra** [comment]
I assumed wrong - the wrapper is not invoked with an input file. I don't know how to solve this, it seems that tying the ghc libdir to a specific component is not a good idea after all

**Pull request closed without merging**
