### PR TITLE
Relax the extra bounds now 1.7 is out with no breaking changes for us

### PR DESCRIPTION
**Pull request by ndmitchell**

### CODE REVIEW

**Comment by fendor** [comment]
Would you need a revision on hackage as well? I dont think we have any new features that would require a release.

**Comment by ndmitchell** [comment]
If we could have a Hackage revision that would be great!

**Comment by fendor** [comment]
Done https://hackage.haskell.org/package/hie-bios-0.4.0

**Comment by ndmitchell** [comment]
Thanks!

**Pull request merged**
