### PR TITLE
Slight refactoring and more doc-comments

### PR DESCRIPTION
**Pull request by masaeedu**
I was reading through the codebase to try and understand what it does and encountered a bit that was a bit confusing to read. I tried breaking it apart a bit and added some doc comments, hopefully you agree that this represents a slight improvement.

I also encountered a type that doesn't seem to be used by any of the functions that ask for it (they use an `_` prefixed variable to discard it). Can this type just be removed?

### CODE REVIEW

**Comment by jneira** [comment]
Hi, thanks for the pr, the comment and refactor of implicitCongi looks good.
Not sure about removing CradleOpts though, maybe @fendor could help us to understand why it exists.

**Comment by masaeedu** [comment]
@jneira In the interests of making this easier to review I've removed the CradleOpts stuff and will put that in a separate PR.

**Review by jneira — APPROVED** [review]
Thanks for separate it in another pr, lgtm

**Review by fendor — COMMENTED** [review]
Nice, thank you!

**Pull request merged**
