### PR TITLE
HIE_BIOS_ARG not passed to the dependencies program

### LINKED ISSUE #234: Bios dependencies program is not passed at target as argument
Actually, there is another issue for me. The documentation says that `dependency-program` is called with no arguments, but that is inconsistent with `program` and doesn't really work for us. Is that by accident or by design?

_Originally posted by @pepeiborra in https://github.com/mpickering/hie-bios/pull/233#issuecomment-672847740_

### PR DESCRIPTION
**Pull request by pepeiborra**
Follow up to #233 in order to fix #234

### CODE REVIEW

**Comment by fendor** [comment]
I have no idea why the tests fail... maybe github does not understand cmd? O

**Comment by fendor** [comment]
The tests are broken on windows in general... So, unrelated to your changes.

**Comment by pepeiborra** [comment]
This is ready to merge (and release please)

**Comment by fendor** [comment]
Release will be later this day

**Pull request merged**
