### PR TITLE
Dont resolve symlinks in cradle discovery

### PR DESCRIPTION
**Pull request by fendor**
Prefer 'makeAbsolute' over 'canonicalizePath'

Solves the problem described in #218 but I am not sure if it would break something

### CODE REVIEW

**Comment by fendor** [comment]
cc @bubba would you mind to give a review here as well?

**Comment by fendor** [comment]
@bubba `canonicalizePaths` resolves symlinks, which caused the issue #219. with makeAbsolute, weonly prepend the current directory and normalise it, remove indirections, etc... but do not resolve symlinks. I am not sure what could break from it and how to add a proper test-case for symlinks

**Comment by bubba** [comment]
Ah, I skimmed the last crucial sentence of that issue. You can add symbolic links in git (last time I checked), so maybe just a folder like
```
- hie.yaml
- foo/ -> bar/
- bar/
```
Where hie.yaml is
```
cradle:
    multi:
        - path: "./foo"
          config: { cradle: { default:  } }
```
And then test that you can get the cradle for `/foo/A.hs`

**Comment by fendor** [comment]
Added failing test-case. I decided to solve it programmatically, since I can not add this symlink to the sdist tar archive (or at least, I expect troubles and pain).

I verified that the test-case used to fail and doesnt anymore.

**Pull request merged**
