### PR TITLE
ghc-9.0.1 support

### PR DESCRIPTION
**Pull request by jneira**
* Using ghc-api-compat head
* The hard work was done by @fendor
* Only 2 libs with allow-newer!

### CODE REVIEW

**Comment by jneira** [comment]
ghc-api-compat does not suport ghc-8.4, time to drop support for it?

**Comment by fendor** [comment]
I would rather try to attempt adding ghc-8.4 support to ghc-api-compat. I mean, how hard can that be? (famous last words)

**Comment by anka-213** [comment]
Does any downstream consumers of this library support ghc-8.4? 
Haskell Language Server/ghcide only supports ghc-8.6 and up, and judging from this list, there are not that many other users: https://packdeps.haskellers.com/reverse/hie-bios

**Comment by fendor** [comment]
I am honestly not aware of any other consumers of this library

**Comment by anka-213** [comment]
Should we just drop ghc-8.4 support then?

**Comment by fendor** [comment]
If no one objects, sure

**Comment by jneira** [comment]
Superseded by #300

**Pull request closed without merging**
